test login and build

diff --git a/.gitlab-ci/containers.yml b/.gitlab-ci/containers.yml
--- a/.gitlab-ci/containers.yml
+++ b/.gitlab-ci/containers.yml
@@ -3,10 +3,27 @@ container:
   parallel:
     matrix:
       - RUNNER_TAG: [debian]
+  before_script:
+    -|
+     echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
+
   script:
     - |
-       env | grep CI | sort;
-  allow_failure:
+      PODMAN=$(which podman);
+      DOCKER=$(which docker);
+      declare -i exit_status=0;
+      if [ -n "${PODMAN}" ]; then
+         CONTAINER_APP="${PODMAN}";
+      elif [ -n "${DOCKER}" ]; then
+         CONTAINER_APP="${DOCKER}";
+      else
+        echo "[ERROR] podman or docker not present in environment."
+        exit 1;
+      fi;
+      #${CONTAINER_APP} build -t gitlab01.brunoe.net:5050/ebruno/softwaretrace-ostools/rhel10rpmbuild -t rhel10rpmbuild -f rhel10/Containerfile;
+      ${CONTAINER_APP} build -t ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE_SLUG}/${CI_PROJECT_NAME}/rhel10rpmbuild -t rhel10rpmbuild -f rhel10/Containerfile;
+      ${CONTAINER_APP} images;
+    allow_failure:
     exit_codes:
       - 1
 
