add registery logout

diff --git a/.gitlab-ci/containers.yml b/.gitlab-ci/containers.yml
--- a/.gitlab-ci/containers.yml
+++ b/.gitlab-ci/containers.yml
@@ -5,7 +5,21 @@ container:
       - RUNNER_TAG: [debian]
   before_script:
     - |
-     echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
+      if [ -x /usr/bin/podman ]; then
+        PODMAN="podman";
+      fi;
+      if [ -x /usr/bin/docker ]; then
+          DOCKER="docker";
+      fi;
+      if [ -n "${PODMAN}" ]; then
+         CONTAINER_APP="${PODMAN}";
+      elif [ -n "${DOCKER}" ]; then
+         CONTAINER_APP="${DOCKER}";
+      else
+        echo "[ERROR] podman or docker not present in environment.";
+        exit 1;
+      fi;
+     echo "$CI_REGISTRY_PASSWORD" | ${CONTAINER_APP} login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
 
   script:
     - |
@@ -107,7 +121,23 @@ container:
         fi;
       done < "${tmpfile}";
       rm -r -f "${tmpfile}";
-      echo "[INFO] end of script at line number $LINENO"
+      echo "[INFO] end of script at line number $LINENO";
+  after_script:
+      if [ -x /usr/bin/podman ]; then
+        PODMAN="podman";
+      fi;
+      if [ -x /usr/bin/docker ]; then
+          DOCKER="docker";
+      fi;
+      if [ -n "${PODMAN}" ]; then
+         CONTAINER_APP="${PODMAN}";
+      elif [ -n "${DOCKER}" ]; then
+         CONTAINER_APP="${DOCKER}";
+      else
+        echo "[ERROR] podman or docker not present in environment.";
+        exit 1;
+      fi;
+     echo ${CONTAINER_APP} logout $CI_REGISTRY;
   tags:
      - $RUNNER_TAG
 
